create database customer_behavior;
use customer_behavior;

select * from customer;

-- Q1.What is the total revenue generated by male vs female Customer?
select gender,sum(purchase_amount) 
from customer 
group by gender;

-- Q2. which customer used a discount, but still spent more than average purchase amount
select customer_id, purchase_amount 
from customer 
where discount_applied = 'yes' and purchase_amount >= (Select avg(purchase_amount) from customer);

-- Q3. which are the top five products with the highest average review rating? 
select item_purchased, round(avg(review_rating),2) as average_rating
from customer
group by item_purchased
order by average_rating desc
limit 5;

-- Q4 Compare the average purchase amount with standard and express shipping 
select shipping_type, round(avg(purchase_amount),2) 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5 Do subscribe customer spends more compare spent and total revenue between substance and non-subscribers, 
select subscription_status, count(customer_id) as total_customer, round(avg(purchase_amount),2) as avg_spend, round(sum(purchase_amount),2) as total_revenue
from customer
group by Subscription_status
order by total_revenue, avg_spend desc;

-- Q6 which five product have the highest percentage of purchase with discounts applied 
select item_purchased, 
round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 segment customers into new returning and based on the total number of previous purchase and show the count of each segment. 
WITH customer_type AS ( 
    SELECT 
        customer_id, 
        previous_purchases, 
        CASE 
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer
)

SELECT 
    customer_segment, 
    COUNT(*) AS no_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8 What are the top three most purchased products within each category, 
WITH item_counts AS ( 
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        DENSE_RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9 Are customers who are repeat buyers (more than five previous purchase) also like you to subscribe, 
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 what is the revenue contribution of each age group.

select age_group, 
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;